name: df-parallel
  
channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - jupyterlab=3
  - requests
  - pandas
  - pyarrow
  - dask
  - pyspark=3.2.1
  - openjdk=8.0.152

variables:
  SPARK_CONF_DIR: ../conf
