name: df-parallel-gpu
  
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - jupyterlab=3
  - dask=2022.5.1
  - pyspark=3.2.1
  - openjdk=8.0.152
  - cudf=22.04
  - dask-cudf=22.04.00
  - cudatoolkit=11.5

variables:
  # SPARK conf directory contains logging configuration
  SPARK_CONF_DIR: ../conf
