name: df-parallel 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.7
  - jupyterlab=3
  - jupyter-offlinenotebook
  - pandas=1.3.5
  - pyarrow=7.0.0
  - dask
  - pyspark=3.2.1
  - openjdk=8.0.152
  - requests
  - ipywidgets=7.6.2
  - conda-pack=0.7.0
  - matplotlib=3.5.2
