name: df-parallel
  
channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.9
  - jupyterlab=3
  - ipywidgets=7.7.1
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - papermill=2.3.4
  - dask=2022.05.2
  - pyspark=3.3.0
  - pyarrow=8.0.1
  - openjdk=11.0.15

variables:
  # SPARK conf directory contains logging configuration
  SPARK_CONF_DIR: ../conf
  SPARK_DRIVER_MEMORY: 16G
  SPARK_DRIVER_MAXRESULTSIZE: 4G
  SPARK_WORKER_MEMORY: 4G
