name: df-parallel
  
channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - jupyterlab=3
  - ipywidgets
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - papermill=2.3.4
  - dask=2022.7.1
  - pyarrow=7.0.0
  - pyspark=3.2.1
  - papermill=2.3.4
  - openjdk=8.0.152

variables:
  # SPARK conf directory contains logging configuration
  SPARK_CONF_DIR: ../conf
