name: df-parallel 

channels:
  - rapidsai
  - nvidia
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - jupyterlab=3
  - pandas=1.3.5
  - pyarrow=7.0.0
  - dask=2022.5.0
  - pyspark=3.2.1
  - openjdk=8.0.152
  - requests
  - ipywidgets=7.6.2
  - conda-pack=0.7.0
  - matplotlib=3.5.2
  - faker=13.11.1
  - cudf=22.04
  - cudatoolkit=11.5
